// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCWjrSsdMATm1wMlMzEDkiOk5ekC8otTY',
    appId: '1:108956436614:web:8a45a20dedf1c886776907',
    messagingSenderId: '108956436614',
    projectId: 'todolisttesting-c2f77',
    authDomain: 'todolisttesting-c2f77.firebaseapp.com',
    storageBucket: 'todolisttesting-c2f77.appspot.com',
    measurementId: 'G-QWRCSEWTZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-bNVeslHwdSlz6qpBuadMBB4FEB5yTCQ',
    appId: '1:108956436614:android:f1641af9e5c76830776907',
    messagingSenderId: '108956436614',
    projectId: 'todolisttesting-c2f77',
    storageBucket: 'todolisttesting-c2f77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6HKCxVzK4p22OscfbznfwvztGV-uJfs4',
    appId: '1:108956436614:ios:ce80d8d7af435b55776907',
    messagingSenderId: '108956436614',
    projectId: 'todolisttesting-c2f77',
    storageBucket: 'todolisttesting-c2f77.appspot.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6HKCxVzK4p22OscfbznfwvztGV-uJfs4',
    appId: '1:108956436614:ios:873f18f93baffd21776907',
    messagingSenderId: '108956436614',
    projectId: 'todolisttesting-c2f77',
    storageBucket: 'todolisttesting-c2f77.appspot.com',
    iosBundleId: 'com.example.todoList.RunnerTests',
  );
}
